version: "3.12"


services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8999:8999"
    volumes:
      - ./app:/app
    command: >
        sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8999"
    environment:
      - DB_HOST=postgres
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672/VHOST
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - rabbitmq


  postgres:
    image: postgres:13-alpine
    ports:
      - "5499:5499"
    volumes:
      - dev-db-data:/C/Program Files/PostgreSQL/15/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI



  # celery-worker1:
  #   container_name: celery-worker1
  #   build:
  #     context: ./celery_worker
  #     dockerfile: Dockerfile
  #     args:
  #       - DEV=true
  #   command: >
  #     celery -A celerytask worker --hostname=worker-spear-serverA@%h --loglevel=info --concurrency=1 -E
  #   volumes:
  #     - ./celery_worker:/app
  #   environment:
  #     - ALLOWED_HOSTS=localhost,app
  #     - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
  #     - CELERY_BACKEND=redis://redis:6379/0
  #     - QUEUE_API_HOST=app
  #     - QUEUE_API_PORT=8080
  #     - TIMEZONE=Europe/Amsterdam


  # celery-worker2:
  #   container_name: celery-worker2
  #   build:
  #     context: ./celery_worker
  #     dockerfile: Dockerfile
  #     args:
  #       - DEV=true
  #   command: >
  #     celery -A celerytask worker --hostname=worker-spear-serverB@%h --loglevel=info --concurrency=1 -E
  #   volumes:
  #     - ./celery_worker:/app
  #   environment:
  #     - ALLOWED_HOSTS=localhost,app
  #     - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
  #     - CELERY_BACKEND=redis://redis:6379/0
  #     - QUEUE_API_HOST=app
  #     - QUEUE_API_PORT=8080
  #     - TIMEZONE=Europe/Amsterdam


  flower:
    image: mher/flower
    container_name: flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq


  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  dev-db-data: